### ISSUE TITLE
Load images

### ISSUE THREAD

**Issue by AbrahamAlcaina** [mjohnston/react-native-webpack-server#21]
Hey, 
One question, I'm try to load an image.  In the normal way as is it:

``` javascript
<Image 
    sytle = {style.image}
    source={require('image!./logo.jpg')}>
</Image>
```

But it is not working. 
I try to use some loader :

```
{ test: /\.(jpe?g|png|gif)$/i, exclude: /node_modules/, loader: 'file-loader'}
```

```
{ test: /\.(jpe?g|png|gif)$/i, exclude: /node_modules/, loader: 'url-loader'}
```

But isn't work, Any ideas?

**Comment by AbrahamAlcaina** [comment]
I also try

``` javascript
                    <Image 
                        sytle = {style.image}
                        source={require('image!logo.jpg')}>
                        <Text
                            style={style.title}>
                            theme : {this.props.theme.id}
                        </Text>
                    </Image>
```

With the loader 
https://github.com/willpiers/react-native-image-loader

``` javascript
  module: {
    loaders: [
      { test: /\.js$/, exclude: /node_modules/, loaders: ['babel?stage=0&blacklist=validation.react']},
      { test: /\.jsx$/, exclude: /node_modules/, loaders: ['babel?stage=0&blacklist=validation.react']},
      { test: /\.json$/i, loader: 'json' }, 
      { test: /\.jpg$/i, exclude: /node_modules/, loaders: ['react-native-image']}
    ],
```

**Comment by mjohnston** [comment]
You should be able to use the `require('image!filename.png')` format as prescribed in the React Native docs. This gets transformed by webpack into `{uri: 'filename.png', isStatic: true}`.

I'm not sure if React Native supports relative paths as in your first example. Can you try replacing `image!./logo.jpg` with `image!logo.jpg`. And make sure the image has been added to your Xcode project.

Also, if you are on an older version of React Native JPEGs are not supported (only PNG).

**Comment by AbrahamAlcaina** [comment]
Thanks for your time @mjohnston, I forget to add the image to xcode project.
Noov issue :disappointed: 
BTW the correct form is `source={require('image!logo.jpg')}`

**Comment by salbito** [comment]
@AbrahamAlcaina 

Sorry, I understand that this issue is old but could you share what you ended up doing? Do you need to modify the webpack config to use the file-loader or react-native-image loader? I've already added the image to xcode but it still does not appear for me.

**Comment by cowfox** [comment]
Given the current status of `react-native-webpack-server` and `react native`, I would recompensed **not** to use `webpack` to help do the bundling. Couple of reasons: 
- `React Native` implements its own `Babel` preset to help transform the code of `React Native` in its recent versions. It is working good and I have no reason to keep using it. 
- The current `React Native` CLI also provides its own app building CMD, and it supports both iOS and Android quite well. It also adds a special bash script into its new Xcode project template `/node_modules/react-native/packager/react-native-xcode.sh` and I think it is good to be just stick to it. 
- Working with Jest and Webpack needs **a lot** effort to set it up, **and** it does not handle well with the "static assess" (like images, CSS). 
- The last, which is the most important, the latest `React native` version (starting from `0.14`), it adds support for images with **relative** path!! Now `<Image source={require('./my-icon.png')} />` works just fine. And it also support **suffix** (like `@2x`, `@3x`, etc.). 

Ref: https://facebook.github.io/react-native/docs/images.html

---

This project `react-native-webpack-server` is still a project with great potential. I have used it probably since beginning since I'm familiar with Webpack eco system. I'm looking for it to be back with regular development and maintenance.
