### ISSUE TITLE
Dynamic loading of bundles based on URL

### ISSUE THREAD

**Issue by jsierles** [mjohnston/react-native-webpack-server#24]
For the [React Native Playground](http://rnplay.org), we're using the standard packager, but would like to switch to this for hot reloading support.

Each app hosted there writes its javascript file to disk, and the ios app loads the corresponding bundle.

However, with webpack it looks like there's no way to specify an arbitrary entry point based on the URL. This issue looks related but unresolved: https://github.com/webpack/webpack/issues/118

I'd love to know if you could suggest an alternative solution. Cheers!

**Comment by jsierles** [comment]
I should also mention that the goal is to have the apps share the react native code, and not have to run a server for each app.

**Comment by mjohnston** [comment]
How is it currently working with the standard packager? Do you have each app's entry JS sitting at the packager root?

e.g.

```
/path/to/packager/root/app-1.js => http://packager.rnplay.org/app-1.js.bundle
/path/to/packager/root/app-2.js => http://packager.rnplay.org/app-2.js.bundle
```

Webpack requires that each entry be defined in the config file. One thing you could do is create the RN webpack server yourself (instead of using `bin/react-native-webpack-server start`), passing it a webpack config object that you create based on the registered app IDs.

Check [here](https://github.com/mjohnston/react-native-webpack-server/blob/master/bin/react-native-webpack-server.js) for an example.

The gotcha here is that there is no way (that I know of at least) to update the webpack config without restarting the server. So any time a new app ID is registered you would have to restart it.

**Comment by jsierles** [comment]
Currently yes, each app's entry js is at the root.

Re: webpack, I figured as much. For now, restart might be OK, but I'm guessing it will break current users hot loader sessions due to cutting off the websocket.

**Comment by mjohnston** [comment]
Another thing - you can't hot reload components if they are in the entry JS, which looks like the default setup in RNPlayNative. If you want hot load for components you'll need a way to split the app into multiple files.

**Comment by jsierles** [comment]
Yeah - this is certainly doable. Will give it a try.
