### ISSUE TITLE
3rd party libs that reference subrequires of react-native blow up

### ISSUE THREAD

**Issue by nevir** [mjohnston/react-native-webpack-server#87]
For example, [react-native-vector-icons references 'private' modules within react-native](https://github.com/oblador/react-native-vector-icons/blob/master/lib/create-icon-set.js#L17-L20) with requires like this:

``` jsx
var StyleSheetPropType = require('react-native/Libraries/StyleSheet/StyleSheetPropType');
var flattenStyle = require('react-native/Libraries/StyleSheet/flattenStyle');
var ViewStylePropTypes = require('react-native/Libraries/Components/View/ViewStylePropTypes');
var TextStylePropTypes = require('react-native/Libraries/Text/TextStylePropTypes');
```

This results in webpack freaking out (since this path isn't whitelisted for babel).

If I add `react-native` to babel's whitelist, all hell breaks loose, due to React's modules all being top level.

**Comment by elliottsj** [comment]
react-native-webpack-server is designed to [register all internal react-native modules as webpack externals](https://github.com/mjohnston/react-native-webpack-server/blob/master/lib/getReactNativeExternals.js), so that the RN packager resolves any internal modules. If you modify react-native-vector-icons like this:

``` js
var StyleSheetPropType = require('StyleSheetPropType');
var flattenStyle = require('flattenStyle');
var ViewStylePropTypes = require('ViewStylePropTypes');
var TextStylePropTypes = require('TextStylePropTypes');
```

Then it should work.

We want to avoid loading react-native internal modules in _both_ webpack and the RN packager because some modules (like `RCTDeviceEventEmitter`) need to have a consistent internal state: https://github.com/magus/react-native-facebook-login/pull/25
